name: Test Secrets Output

on:
  workflow_dispatch:

jobs:
  test-secret-output:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [FOO_ENV_12, FOO_ENV_13, FOO_ENV_14, FOO_ENV_15, FOO_ENV_16, FOO_ENV_17, FOO_ENV_18, FOO_ENV_19, FOO_ENV_20]
    environment: ${{ matrix.environment }}
    steps:
      - name: Output Secrets
        run: |
          for i in {1..10}
          do
            secret_name="FOO_SECRET_$i"
            secret_value="${!secret_name}"
            echo "$secret_name: ${secret_value:0:1} ${secret_value:1}"
          done
        env:
          FOO_SECRET_1: ${{ secrets.FOO_SECRET_1 }}
          FOO_SECRET_2: ${{ secrets.FOO_SECRET_2 }}
          FOO_SECRET_3: ${{ secrets.FOO_SECRET_3 }}
          FOO_SECRET_4: ${{ secrets.FOO_SECRET_4 }}
          FOO_SECRET_5: ${{ secrets.FOO_SECRET_5 }}
          FOO_SECRET_6: ${{ secrets.FOO_SECRET_6 }}
          FOO_SECRET_7: ${{ secrets.FOO_SECRET_7 }}
          FOO_SECRET_8: ${{ secrets.FOO_SECRET_8 }}
          FOO_SECRET_9: ${{ secrets.FOO_SECRET_9 }}
          FOO_SECRET_10: ${{ secrets.FOO_SECRET_10 }}
